package com.contest.seoul.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "restaurant_error")
public class ErrorRestaurant {


    @DynamoDBHashKey(attributeName = "id") //해당 필드를 HashKey로 설정합니다.
    @DynamoDBAutoGeneratedKey // 자동으로 Key를 생성합니다. UUID를 활용합니다.
    private String id;

    @DynamoDBAttribute  // 해당 필드를 Attribute로 설정합니다.
    private String cggCode;

    @DynamoDBAttribute  // 해당 필드를 Attribute로 설정합니다.
    private Double latitude; // 위도
    @DynamoDBAttribute
    private Double longitude; // 경도
    @DynamoDBAttribute(attributeName = "upsoSno")
    private String upsoSno;  // 업소일련번호
    @DynamoDBAttribute
    private String upsoNm; // 업소명
    @DynamoDBAttribute
    private String siteAddrRd; // 소재지도로명
    @DynamoDBAttribute
    private String siteAddr; // 소재지지번명
    @DynamoDBAttribute
    private String bdngJisgFlrNum; // 지상_부터
    @DynamoDBAttribute
    private String bdngUnderFlrNum; // 지하_부터
    @DynamoDBAttribute
    private String geEhYn; // 모범음식점여부

    @DynamoDBAttribute
    private String num;
}
