package com.contest.seoul.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;


@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "restaurant") //해당 클래스를 엔티티로 설정합니다.
public class RestaurantItem {

    @DynamoDBHashKey(attributeName = "id") //해당 필드를 HashKey로 설정합니다.
    @DynamoDBAutoGeneratedKey // 자동으로 Key를 생성합니다. UUID를 활용합니다.
    private String id;

    @DynamoDBAttribute  // 해당 필드를 Attribute로 설정합니다.
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "cggCode") // global secondary index HashKey 설정
    private String cggCode;

    @DynamoDBAttribute(attributeName = "latitude")
    private Double latitude; // 위도

    @DynamoDBAttribute(attributeName = "longitude")
    private Double longitude; // 경도
    @DynamoDBAttribute
    private String asgnYear; // 지정년도
    @DynamoDBAttribute
    private String asgnDate; // 지정일자
    @DynamoDBAttribute
    private String upsoName; // 업소명
    @DynamoDBAttribute
    private String siteAddressRd; // 소재지도로명
    @DynamoDBAttribute
    private String siteAddress; // 소재지지번
    @DynamoDBAttribute
    private String mainFood; // 주된음식
    @DynamoDBAttribute
    private String admdngName; // 행정동명
    @DynamoDBAttribute
    private String sitePhoneNumber; // 소재지전화번호

}